export const TITLE = "חנות המוצרים"
export const GO_CHECHKOUT = "עבור אל התשלום"
export const SHOW_CART = "עבור אל העגלה"
export const NORMAL_ORDER = "סידור ברירת מחדל"
export const CHEAP_ORDER = "סידור מהזול אל היקר"
export const EXPENSIVE_ORDER = "סידור מהיקר אל הזול"
export const FIND_PRODUCT = "חפש מוצר ספציפי כאן..."
