export const TITLE = "תשלום"
export const SEC_TITLE = "שמחים שהחלטתם לקנות! משלוח חינם עלינו :)"
export const NAME = "שם פרטי"
export const LAST_NAME = "שם משפחה"
export const CITY = "עיר"
export const ADRESS = "כתובת מלאה"
export const APPARTMENT_NUM = "מספר דירה"
export const PHONE = "מספר פלאפון"
export const EMAIL = "דואר אלקטרוני"
export const OPTIONAL_DATA = "הערות להזמה"
export const NONE = "במידה ואין נא להשאיר ריק..."
export const SEND = "שליחת הזמנה"

export const EMPTY_CONTENT = "חובה למלא את כל שדות החובה"
export const ERROR_ADDRESS = "נא להזין כתובת מלאה ותקינה"
export const ERROR_PHONE = "נא להזין מספר פלאפון תקין"
export const ERROR_POLICY = "חובה לקרוא ולסמן את תקנון השימוש"