export const TITLE = "העגלה שלך"
export const SHOW_CART = "עבור אל העגלה"
export const GO_CHECHKOUT = "עבור אל התשלום"
export const EMPTY_CART = "העגלה שלך ריקה..."
export const SUBTOTAL = "סך הכל לתשלום: "
export const DELETE_SUCCESS = "המוצר נמחק מעגלת הקניות בהצלחה"
